### ISSUE TITLE
Problem with DS and AmbientSounds?

### ISSUE THREAD

**Issue by ShadowSonic42** [OreCruncher/DynamicSurroundings#158]
*Mod Version:*
1.10.2-3.4.7.1

*Forge Version:*
2477

*Description:*
I have AmbientSounds with DS, causing the sound to mute when I go near water with many entities swimming, that would normally cause the water bobbing sound. I have tested without AmbientSounds, and everything works without it installed. I think it might be a conflict issue between DS and AmbientSounds because I have a modpack with both of them installed, and other mod sounds are working, except for DS. I have also tested with just DS and AmbientSounds, that is when the issue happens.
[Example vid of AmbientSounds and DS](https://drive.google.com/open?id=0BzxU6EKR1oN7WU1OQWZzam5PVzg)
[Example vid of just DS](https://drive.google.com/open?id=0BzxU6EKR1oN7b3ZGVGVKT3Nhem8)

**Comment by OreCruncher** [comment]
DS has built in some logic that detects when the max number of sounds are queued up in the sound engine and does not play further sounds until there is room.  With all that sound occuring it could be that max sounds have been reached.

To check you can turn on debug logging in DS, and then hit F3 when hear the water where all the mobs are located.  DS enumerates all the sounds that are playing in the debug display along with their counts.  IIRC the threshold for "self muting" is about 176 sounds or so.

**Comment by ShadowSonic42** [comment]
So how would I go about fixing the problem?

**Comment by OreCruncher** [comment]
Well, in this particular case you can tag the bubble sound to be culled.  It will reduce the frequency that the sound will play.  This assumes, of course, the situation I outline above is what is happening.

**Comment by ShadowSonic42** [comment]
After playing for a bit longer, this [happened.](https://drive.google.com/open?id=0BzxU6EKR1oN7T3FBSFpKMkRrT00)

**Comment by OreCruncher** [comment]
I see that the max number of sounds is 32.  You change the configuration any?  If not I will need a client log - there is a mod conflict somewhere.

**Comment by ShadowSonic42** [comment]
From what I can tell, the config for Ambient Sounds only is for enabling or disabling sounds and a debugging option, nothing else. [Log](https://pastebin.com/FVpQuFVA)

**Comment by ShadowSonic42** [comment]
So I did another test to see if I could change the max amount of sounds that could play at once. By what you said earlier, I would assume that the sound system was not meant to be a max of 32 sounds. So I went ahead and disabled Ambient Sounds to see if that number would change. The max after that was 192 sounds. Then is the problem with DS not working with Ambient Sounds, or the other way around?

**Comment by OreCruncher** [comment]
Default vanilla configures the sound engine to a max of 32 sounds.  Dynamic Surroundings ups it to some fraction of the max sound channels for the players hardware.  (Modern sound systems allow on average 256 sound channels.)  [Ambient Sounds configures the number of sound channels as well and looks to be overriding what DS sets](https://github.com/CreativeMD/AmbientSounds/blob/1.11/src/main/java/com/creativemd/ambientsounds/TickHandler.java#L256).  Ideally Ambient Sounds should allow for tuning these values rather than hard coding them.

**Comment by ShadowSonic42** [comment]
So there is no way for me, nor you, to be able to fix this unless the developer for Ambient Sounds allows for the amount of channels to be changed?

**Comment by OreCruncher** [comment]
At the moment I can't think of anything you can do to make it work.  I will have to think on what I could do on my end to work around it.

**Comment by OreCruncher** [comment]
@ShadowSonic42 Try out this test jar located (here)[https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.7.2T3].  I changed how the sound system is initialized so it should help.

**Comment by ShadowSonic42** [comment]
I have tested with the new jar, and I still have the same results.
[Results with AS](https://drive.google.com/open?id=0BzxU6EKR1oN7TDdjMDVHMUp4WkU)
[Results with only DS](https://drive.google.com/open?id=0BzxU6EKR1oN7dWJNNHNFTnM4N00)

**Comment by OreCruncher** [comment]
@CreativeMD At this point, then, I would think a change would have to be made in Ambient Sounds.

**Comment by ShadowSonic42** [comment]
[fml client latest](https://pastebin.com/WkUEBRLi)
[lastest log](https://pastebin.com/4FiShTUF)

**Comment by OreCruncher** [comment]
```
[10:33:58] [Client thread/INFO] [dsurround/]: Sound channels: 176 normal, 16 streaming (total avail: 192)
[10:33:58] [Client thread/INFO] [dsurround/]: Stream buffers: 3 x 131072
```
My mod set the channels the way it expects.  I suspect that AS is changing them back at some point after.

**Comment by ShadowSonic42** [comment]
DS is setting the amount of channels, then AS later changes them? If that is the case, is there a way to make it so AS loads first then DS overrides that?

**Comment by OreCruncher** [comment]
Its not a question of mod loading, its a question as to when what code runs.  DS sets the number of channels *after* the normal sound setup event.  I believe the AS code is executing sometime after that under some other conditions.  I haven't had a chance to trace actual execution in my debug environment.

**Comment by OreCruncher** [comment]
Made another tweak to see if I can alter the flow.  Find it [here](https://github.com/OreCruncher/DynamicSurroundings/releases/tag/v3.4.7.2T4).

**Comment by ShadowSonic42** [comment]
Tested, and sadly still same results. 
[Results](https://drive.google.com/open?id=0BzxU6EKR1oN7Y1hSNTh4SUZleEU)

**Comment by ShadowSonic42** [comment]
I have done some more tests on the second issue, and it seems to be with sound physics. The sounds do play, they are just very quiet, Mod Version: v3.4.7.2T4

**Comment by ShadowSonic42** [comment]
I have just revert to an older version of DS, version 3.4.7.1, and the problem with with sound physics was fixed, but the AS problem was still broken.

**Comment by OreCruncher** [comment]
From what I recall Sound Physics does funky things with sound volumes.  In general I say its not compatible.  I personally use Sound Filters.

**Comment by CreativeMD** [comment]
@OreCruncher The sound engine has 4 streaming channels per default , which is not enough for AmbientSounds, so i changed it ([forum thread](http://www.paulscode.com/forum/index.php?topic=14927.msg29452#msg29452)). Once I found that DS does change those values as well, I added `@SubscribeEvent(priority = EventPriority.LOW)` to my method, so my configuration will be set after yours. Otherwise there would have been many issues if DS is installed (would ruin compatibility).

I added a config option for streaming and normal channels count (versions should be available soon). Hope this fixes this issue.

**Comment by ShadowSonic42** [comment]
@CreativeMD I have updated AS to the lastest version, v2.0.8,  and I also changed the config. I have set the normal and streaming channels to the values that DS, v3.4.7.2, would have set them to.
[AS config](https://pastebin.com/7FcnuQuh)

But, I got the same results as before I updated.
[Look at the soundsystem on the side](https://drive.google.com/open?id=0BzxU6EKR1oN7U3J6OXVReFRfbmM)

**Comment by CreativeMD** [comment]
The sound engine configuration says that they may only be 32 channels in total. So maybe you don't have 176 normal channels, but 16. Just try to use less streaming channels and see if this fixes it.

**Comment by OreCruncher** [comment]
I think his system has more than 32.  I looked at a [provided log](https://github.com/OreCruncher/DynamicSurroundings/issues/158#issuecomment-330061481) and based on the trace it appears to have 256 channels for the system.

**Comment by ShadowSonic42** [comment]
@CreativeMD I changed the values to be lower than 32 to see if the config is working, or my system wasn't powerful enough.
[New Config](https://pastebin.com/6G7ETgGd)

As you can see, the total amount of channels should be less than 32.
[But that didn't change the value](https://drive.google.com/open?id=0BzxU6EKR1oN7YVNZdWZJZ2Ftb2s)

**Comment by CreativeMD** [comment]
@ShadowSonic42 Not less than 32, but 32 in total meaning something like: 8 streaming channels and 24 normal channels.

**Comment by ShadowSonic42** [comment]
But if I changed the values to be less than 32, shouldn't they change to that instead?

**Comment by CreativeMD** [comment]
If you only have 32 channels available and set 16 streaming channels. There are only 16 channels left. Setting the config to 16 normal channels will not change anything either, since the engine can also have less than 32 channels. So just increase this number to 24 and see if something changes.

In my eyes it's rather obvious that this issue is caused by a lack of available normal channels, so increasing those should fix it. You could also try out the vanilla configuration, of 4 streaming and 28 normal channels.

**Comment by ShadowSonic42** [comment]
@CreativeMD Problem still exists with [24 normal channels and 8 streaming](https://pastebin.com/A7pfL60V) (your recommended)
[DS sounds aren't playing when many sounds are in the area](https://drive.google.com/open?id=0BzxU6EKR1oN7VklHcTliRHNzYTA)

And problem still exists with [28 normal channels and 4 streaming](https://pastebin.com/nNuh3zb5)  (default)
[Same result as above](https://drive.google.com/open?id=0BzxU6EKR1oN7Rng0S1l6UDZoV00)

But without AS installed the issue goes away and I have [176 normal and 16 streaming](https://pastebin.com/QwnbKnR3) (DS settings)
[Total amount of sounds on left side](https://drive.google.com/open?id=0BzxU6EKR1oN7OXZwQXpRLWM3aUU)

But as you saw earlier, changing the amount of channels in the config to be more than 32, did not change it to that value, which could be the problem.

**Comment by CreativeMD** [comment]
That is weird, but i don't think there is any way for me to fix it. I think those are just the limit of the sounds engine :(

**Comment by ShadowSonic42** [comment]
@CreativeMD Maybe you could ask @OreCruncher on what he did with DS or figure out how to make it so DS algorithm is prioritized over AS. IDK just a suggestion.

**Comment by CreativeMD** [comment]
I'm sorry to disappoint you, but i doubt that there is an easy way to fix it.

**Comment by Phalaaange** [comment]
Hey man, did you mange to find a way fixing your problem?
I got similar issue that in-game music don't play (like ever), possibly due to AS and DS taking up streaming channel always?
Maybe I should increasing the number of channels signed to streaming and test a bit .

**Comment by OreCruncher** [comment]
FYI - I am going to be doing some testing with Ambient Sounds and DS this week.  I will see if it still occurs with the latest mod versions.

**Comment by OreCruncher** [comment]
@CreativeMD 

OK.  Loaded up the latest of both DS and Ambient Sounds.  DS initializes the sound channels within the SoundSetupEvent Forge fires.  It configures the channels to what DS wants.  Later on, AmbientSounds sets the channels in its FMLInitializationEvent handler.  The decompiled codes shows it is setting the streaming/normal channels to 11/21 respectively overriding what DS is doing.  The values that AmbientSounds are using appear to be hard coded based on what I see in the JAR.

My recommendation is for AmbientSounds to configure the sound channels in response to the SoundSetupEvent (at a priority higher than LOWEST since DS is registered there).  This will allow DS to override whatever AmbientSounds want and I think everything will be happy.

**Comment by CreativeMD** [comment]
@OreCruncher sorry, i completely forgot to answer.
We talked about this before. AmbientSounds requires more streaming channels per default, so it's overwriting the changes of DS (otherwise the mods could not run alongside each other without further configuration). You can configure the number of channels in the config file (at least in the newer versions).

**Comment by OreCruncher** [comment]
The source I looked at was from github and the JAR came from CurseForge.  DS sets 16 streaming channels, and AS sets 11. :)

**Comment by CreativeMD** [comment]
DS used to set less back then. 
I added configuration a few months ago:
https://github.com/CreativeMD/AmbientSounds/blob/1.12/src/main/java/com/creativemd/ambientsounds/TickHandler.java#L258

**Comment by OreCruncher** [comment]
I think this stomps on that: https://github.com/CreativeMD/AmbientSounds/blob/1.12/src/main/java/com/creativemd/ambientsounds/AmbientSounds.java#L73

**Comment by CreativeMD** [comment]
Oh right, those don't matter, they are fired during startup. I forgot to remove them.

**Comment by xhatz** [comment]
Hello! I see this thread is still active, have you find any solution yet ^^?

I don't know if I have the same problem, but it seems like when I have the two mods installed, sometimes the sounds from DS just stops for a moment (ex: I don't hear my footsteps for a few seconds, then I hear them again)...

Thank you!

**Comment by OreCruncher** [comment]
I'm pretty sure we know the issue.  The sounds of DS stopping is because DS does sound throttling - if the number of sounds down in the sound engine is near the maximum number of channels it won't play a sound.  Currently waiting on a code adjustment for AS. :)

**Comment by CreativeMD** [comment]
You can configure the number of channels in AmbientSounds, but i'm not sure whether this will fix this issue or not. The sound engine only allows 32 channels at the same time. If there are not enough channels available (too many sounds are played at the same time) a sound will not be played.

**Comment by OreCruncher** [comment]
[The bug is still in the code on Github](https://github.com/CreativeMD/AmbientSounds/blob/1.12/src/main/java/com/creativemd/ambientsounds/AmbientSounds.java#L73).  Modern computers have sound cards that support up to 256 channels.  It's why I have that check down in the sound config of DS.

**Comment by CreativeMD** [comment]
@OreCruncher it doesn't matter, it doesn't change anything at all.
@xhatz you can try to increase the number of channels, maybe this fixes the issue (if orecruncher is right you can set more channels than 32).

**Comment by OreCruncher** [comment]
@CreativeMD That's weird.  I tweaked DS to redo the sound channel config during my init phase after AS init phase runs (the code link above) and I get the proper number of sound channels DS expects.

**Comment by CreativeMD** [comment]
Yes. but AS changes the number of channels before the sound engine will be started: https://github.com/CreativeMD/AmbientSounds/blob/1.12/src/main/java/com/creativemd/ambientsounds/TickHandler.java#L258

**Comment by OreCruncher** [comment]
@CreativeMD AS actually sets the sound channels twice - once in the event, and then again in your init phase.  During startup the event fires before the init phase.  So the ordering of what is happening is:

SetupEvent -> AS configs channels (11/32)
SetupEvent -> DS configs channels (16/192) overriding what AS event handler did
Init phase -> AS sets the sound channels back to (11/32), overriding what DS did and whatever the user may have configured in the AS config file.

The change I just committed to DS will re-re-configure the sound channels during the DS init phase, which sets the sound channels back to what DS exepects.

**Comment by CreativeMD** [comment]
@OreCruncher oh ... i will release a fix for it right away. I thought the SetupEvent would be called after the init phase :D

**Comment by OreCruncher** [comment]
No worries.  I am sure the in MC 1.13 the startup sequence will change again. :D

**Comment by CreativeMD** [comment]
Uploaded it, the new version should be available soon.

**Comment by OreCruncher** [comment]
I did check the latest with DS and AS and things work well.  Closing out.  Thanks!

**Comment by Celian136** [comment]
wait, so the lastest versions of AmbientSounds mod and Dynamic Surroundings (both for forge and fabric), for example, from 1 year ago until now are compatible between each other? There's no issues between those two mods anymore? Just to be sure.

**Comment by CreativeMD** [comment]
Pretty sure it all works. But just try it out yourself.
