### ISSUE TITLE
Waterfall sound repeating and not stopping at spot where water meets magma

### ISSUE THREAD

**Issue by Luke616** [OreCruncher/DynamicSurroundings#437]
*Mod Version:*
1.12.2 - 3.4.10.6
*Forge Version:*
14.23.5.2807

*Link to crash log (if applicable):*
N/A
*Description:*
Heard repeating waterfall sound over and over at the spot where a waterfall encountered a magma block. No crash, but the sound persisted even after closing the server and kept playing even throughout the main menu.

**Comment by OreCruncher** [comment]
Are you able to repeat the issue?  If so, can you enable DS debug logging and hit F3 in the area and take a screenshot?  I need to look at the debug screen.

**Comment by SirAron111** [comment]
Not only when waterfall meets magma flowing water in general can make that bug happen i had it in my fountain so i had to remove it but the sound still kept going.

**Comment by SirAron111** [comment]
This is as annoying as the bug with the ender io padding upgrade for the helmet that makes all dyn surround sounds sound like robo stuttering.

**Comment by OreCruncher** [comment]
Try the 3.5.4.2 version.  It has a bunch of changes related to sound handling and stuff.  The x.4.2 version is very close to what is going to be the release version.

As for the ender IO sound padding I have to look at the code.  If the Ender IO function is killing off DS sound plays strange things could happen.

**Comment by Luke616** [comment]
Ah! Can confirm that I also had EnderIO installed when I experienced the above bug. Didn't have any special EIO gear though. I moved to the 3.5.4.2 version of DS and things are working just fine, thanks!

**Comment by SirAron111** [comment]
https://pastebin.com/F1m9jKUQ i found one of the spaming wells and got this from standing near it in the console hope it helps

**Comment by Gamertech** [comment]
This is happening in the latest Dungeons, Dragons and Space Shuttles v3.5c as well.
DS: 3.4.10.6
No EnderIO installed.

Can happen with any flowing water source, but not all of them. After the source is removed, the sound keeps going.

**Comment by ate0ate** [comment]
Can definitely confirm this happening with/without EIO. Seems to happen randomly, but almost always when diverting flowing /falling water or when a machine removes blocks around water. For example, I was using a Mekanism digital miner that was set to replace the blocks it mined with cobble. When this happened on the bottom of a riverbed the sound repetition started happening every time an underwater ore block was replaced with cobblestone. Also very frequent in ravines.

**Comment by OreCruncher** [comment]
I just pushed a release version of 3.5.4.3 to CurseForge.  This should address a lot of the waterfall related issues.  However, there are some corner cases I am still chasing down.  For this case I do not know if this is one of those corner cases.  If you could give it a try and  let me know that would be great.

**Comment by Gamertech** [comment]
Seems to have fixed it, for me at least.

**Comment by EngineOfDarkness** [comment]
There is one thing I noticed with the waterfall sound is that it can cause other sounds to Mute, e.g the footstep sounds just dissappear, equipment "switch" sounds stop playing, ....

This might happen if there are too many waterfall sounds playing at once.

E.g. in my case using Quark Realistic with Worleys Caves and Subterranean Waters causes a lot of waterfalls.

Setting `Waterfall Cutoff` didn't help

The only thing (workaround) that "fixed" the issue instantly for me as

```
        dsurround:waterfall.0 block 
        dsurround:waterfall.1 block 
        dsurround:waterfall.2 block 
        dsurround:waterfall.3 block 
        dsurround:waterfall.4 block 
        dsurround:waterfall.5 block 
```

(basically block the waterfall sound from playing, which I did from the ingame mod configuration)

**Comment by BrisingrAerowing** [comment]
I'm on 3.5.4.3, and I still get this when removing flowing water. Relogging works, and I've gone ahead and disabled the waterfall sounds in my instance. It seems that the code to stop the sound when the water stops flowing is broken.

**Comment by OreCruncher** [comment]
I am fixing a bug related to waterfall handling.  I think it addresses this one as well.  Going to mark it fixed for now.  The change will show up in the next maintenance release (3.5.5.0).

**Comment by OreCruncher** [comment]
Pushed DynamicSurroundings-1.12.2-3.5.5.0 to CurseForge.
